/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2012, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

/* THIS FILE WAS AUTOGENERATED FROM Todotxt.tmLanguage (UUID: 8887f83b-c6dc-4d6c-909a-62bb008f1c8b) */
/****************************************************************
 * IT MIGHT NOT BE PERFECT, PARTICULARLY:                       *
 * IN DECIDING STATES TO TRANSITION TO,                         *
 * IGNORING WHITESPACE,                                         *
 * IGNORING GROUPS WITH ?:,                                     *
 * EXTENDING EXISTING MODES,                                    *
 * GATHERING KEYWORDS, OR                                       *
 * DECIDING WHEN TO USE PUSH.                                   *
 * ...But it's a good start from an existing *.tmlanguage file. *
 ****************************************************************/

define(function(require, exports, module) {
"use strict";

var oop = require("../lib/oop");
var TextHighlightRules = require("./text_highlight_rules").TextHighlightRules;

var TodotxtHighlightRules = function() {
    // regexp must not have capturing parentheses. Use (?:) instead.
    // regexps are ordered -> the first match is used

    this.$rules = { start: 
       [ { token: 'constant.language.todotxt.priority',
           regex: '^\\([A-E]\\)',
           //Todo item priority (can be set to A-E in the mobile application; should be enough for now)
            },
         { token: 'entity.name.tag.todotxt.constant',
           regex: '\\@\\S*',
           //Todo item context
            },
         { token: 'entity.name.tag.todotxt.keyword',
           regex: '\\+\\S*',
           //Todo item project
            },
         { token: 'comment.line.todotxt',
           regex: '^x\\s.*$',
           //Done Todo item
            },
         { token: 'constant.numeric.todotxt.date',
           regex: '([1-2]\\d{3}[-/\\\\.](0?[1-9]|1[012])[-/\\\\.](0[1-9]|[12]\\d|3[01]) ){1,2}',
           //Todo item done or creation date
            },
         { caseInsensitive: true,
           token: 'constant.numeric.todotxt.date',
           regex: '(?:DUE):([1-2]\\d{3}[-/\\\\.](0?[1-9]|1[012])[-/\\\\.](0[1-9]|[12]\\d|3[01]))',
           //Todo item due date
            },
         { caseInsensitive: true,
           token: 'keyword.other.todotxt.wait',
           regex: '[^\\S](?:WAIT)[^\\S]',
           //Todo WAIT command
            } ] }
    
    this.normalizeRules();
};

oop.inherits(TodotxtHighlightRules, TextHighlightRules);

exports.TodotxtHighlightRules = TodotxtHighlightRules;
});